# OIF Solver Configuration Example

[solver]
id = "oif-solver-example"
monitoring_timeout_minutes = 5

[storage]
backend = "file"
[storage.config]
storage_path = "./data/storage"

[account]
provider = "local"
[account.config]
# Example private key from Anvil's default accounts (account #0)
# In production, use environment variables or secure key management
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[delivery]
confirmations = 1
# Configure multiple delivery providers for different chains
[delivery.providers.origin]
rpc_url = "http://localhost:8545"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
chain_id = 31337  # Anvil origin chain

[delivery.providers.destination]
rpc_url = "http://localhost:8546"
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
chain_id = 31338  # Anvil destination chain

[discovery]
# Configure multiple discovery sources
[discovery.sources.origin_eip7683]
rpc_url = "http://localhost:8545"
# InputSettler address on origin chain (where orders are created)
settler_addresses = [
    "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
]

[discovery.sources.destination_eip7683]
rpc_url = "http://localhost:8546"
# OutputSettler address on destination chain (where orders are fulfilled)
settler_addresses = [
    "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
]

[order]
# EIP-7683 order implementations
[order.implementations.eip7683]
# Example OutputSettler address (destination chain)
output_settler_address = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
# Example InputSettler address (origin chain)
input_settler_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"

[order.execution_strategy]
strategy_type = "simple"
[order.execution_strategy.config]
max_gas_price_gwei = 100  # Maximum gas price in gwei

[settlement]
# Direct settlement implementations
[settlement.implementations.eip7683]
rpc_url = "http://localhost:8545"  # Origin chain where oracle is deployed
# Example oracle address from local Anvil setup
oracle_address = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
min_confirmations = 1  # Lower for local testing
dispute_period_seconds = 10  # 10 seconds for local testing