[package]
name = "solver-delivery"
version = "0.1.0"
edition = "2021"

[dependencies]
solver-types = { path = "../solver-types" }
async-trait = "0.1"
solver-account = { path = "../solver-account" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
