# Minimal OIF Solver Configuration Example
# This example demonstrates the essential configuration with templates

# Template definitions for common plugin configurations
[templates.discovery_base]
plugin_type = "eip7683_onchain"
poll_interval_ms = 5000
enable_historical_sync = false

[templates.delivery_base]
plugin_type = "evm_alloy"

[templates.delivery_config_base]
private_key = "${SOLVER_PRIVATE_KEY}"
max_retries = 3
timeout_ms = 30000
enable_eip1559 = true
nonce_management = true
max_pending_transactions = 10

# Core solver settings
[solver]
name = "minimal-oif-solver"
log_level = "info"
http_port = 8080
metrics_port = 9090

# Minimal plugin configuration using templates
[plugins.discovery.ethereum]
enabled = true
template = "discovery_base"

[plugins.discovery.ethereum.config]
chain_id = 1
rpc_url = "${ETH_RPC_URL}"
input_settler_addresses = ["${ETH_INPUT_SETTLER}"]
output_settler_addresses = ["${ETH_OUTPUT_SETTLER}"]
monitor_open = true
monitor_finalised = true
monitor_order_purchased = false

[plugins.delivery.ethereum]
enabled = true
template = "delivery_base"

[plugins.delivery.ethereum.config]
template = "delivery_config_base"
chain_id = 1
rpc_url = "${ETH_RPC_URL}"

# Required: At least one state plugin
[plugins.state.memory]
enabled = true
plugin_type = "memory"

[plugins.state.memory.config]
max_entries = 10000

# Required: Order plugin
[plugins.order.eip7683]
enabled = true
plugin_type = "eip7683_order"

[plugins.order.eip7683.config]
solver_address = "${SOLVER_ADDRESS}"
output_settler_address = "${ETH_OUTPUT_SETTLER}"
input_settler_addresses = ["${ETH_INPUT_SETTLER}"]
oracle_address = "${ETH_ORACLE}"
max_order_age_seconds = 86400
min_fill_deadline_seconds = 300
validate_signatures = true

# Required: Settlement plugin
[plugins.settlement.direct]
enabled = true
plugin_type = "direct_settlement"

[plugins.settlement.direct.config]
rpc_url = "${ETH_RPC_URL}"       # Connect to origin chain where oracle is deployed
oracle_address = "${ETH_ORACLE}"
min_confirmations = 3
dispute_period_seconds = 300
claim_window_seconds = 86400

# Service configurations (minimal required fields)
[delivery]
strategy = "RoundRobin"
fallback_enabled = false
max_parallel_attempts = 1

[settlement]
default_strategy = "direct"
fallback_strategies = []
profit_threshold_wei = "1000000000000000" # 0.001 ETH

[discovery]
realtime_monitoring = true

[state]
default_backend = "memory"
enable_metrics = false
cleanup_interval_seconds = 600
max_concurrent_operations = 50
